# Tea Framework - 服务器配置文件
[framework]
default_server = "default" # 默认服务器, 可以自定义
server_type = "http"       # 服务器类型 - http


[server]
name = "tea"      # 服务器名称
version = "1.0.0" # 服务器版本
mode = "debug"    # 服务器运行模式 - debug, release
ip = "127.0.0.1"  # 服务器IP地址
port = 8000       # 服务器端口号
# host = "localhost"  # 服务器主机名
root_dir = "."              # 服务器根目录
resources_dir = "resources" # 服务器资源目录

routers = "HTTPRouter"       # 服务器路由
listeners = ["HTTPListener"] # 服务器监听器
resources = ["HTTPResource"] # 服务器资源
